### ISSUE TITLE
It gets super slow with 10,000 categories

### ISSUE THREAD

**Issue by MikeRogers0** [MikeRogers0/WP-HTML5-Category-Selector#4]
> What's happening is that if I input text, for example "david" then it will get stuck on the "d" for about a minute. I didn't change anything else on the site.

**Comment by MikeRogers0** [comment]
I'm pretty sure the problem is with https://github.com/MikeRogers0/WP-HTML5-Category-Selector/blob/master/wp-html5-category-selector.js#L33 the listener being on keyup. 

I think the best solution is to swap that out for a `change` if there is a lot of categories, and maybe require two letters.

**Comment by MikeRogers0** [comment]
We could probably also filter with a CSS lookup like `.selectit [data-value*="userString"]`.

**Comment by sparkzilla** [comment]
Requiring two letters is good. I'm a js noob so no other ideas sorry.
